# -*- coding: utf-8 -*-
"""CryptoTredingAlgo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RBirxRP3-CJ26Rrc0604HNGqmbWYQiJC
"""

!pip install yfinance

import yfinance as yf
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.dates import DateFormatter

BTC_CAD = yf.download("BTC-CAD", start='2021-06-22', end='2022-06-22', interval='1d')

BTC_CAD.head()

fig, axs = plt.subplots(dpi=500)

date_format = DateFormatter("%h-%d-%y")

axs.xaxis.set_major_formatter(date_format)
axs.tick_params(axis='x', labelsize=8)

fig.autofmt_xdate()

axs.plot(BTC_CAD['Close'], lw=0.75)

axs.set_ylabel('Price of Bitcoin (CAD)')
axs.set_title('Bitcoin to CAD Exchange Rate')

axs.grid()

plt.show()

